# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [21.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: create env file
        working-directory: .
        run: |
          touch .env
          cat << EOF >> .env
          ${{ secrets.ENV }}

      - name: Checkout app-front repository
        uses: actions/checkout@v4
        with:
          repository: What-s-Your-ETF/app-front
          ref: dev  # branch or tag name from which you want to fetch files

      - name: Copy files
        run: |
          cp -r app-front/project/* ./app-front/project/

      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name wy-etf-codedeploy
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name deploy-group
